# Generated by Django 5.1.7 on 2025-04-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_categori_category_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="Categories",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
