# Generated by Django 5.1.7 on 2025-04-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Services",
            new_name="Service",
        ),
    ]
